feat(90): add new globals components : carousel, slider and section
mathcovax/mon-enorme-tronc pull request #96
Opened 2024-06-05 09:24 UTC by ZeRiix

2024-06-05 09:56 UTC, ZeRiix commented
Si quelqu'un n'aime pas mon css qui se fasse plaisir

2024-06-05 14:59 UTC, mathcovax commented on vue/src/components/TheSlider.vue
tu as inversé l'ordres des balise

2024-06-06 13:11 UTC, Maubry94 commented on duplo/src/fixtures/entities/product.ts
> +	`${faker.random.alpha({ count: 3 })}${faker.random.alphaNumeric(4).toUpperCase()}${faker.datatype.number({ min: 1000, max: 9999 })}`;
Il y a pas mal de trucs deprecated ici. Il faudrait améliorer ça.

2024-06-06 13:12 UTC, Maubry94 commented on vue/src/components/TheCarousel.vue
> +<style scoped>
Pas possible de faire en tailwind ?

2024-06-06 13:12 UTC, Maubry94 commented on vue/src/components/TheSection.vue
> +<style scoped>
Pas possible de faire en tailwind ?

2024-06-06 13:14 UTC, Maubry94 requested changes
Riviewed

2024-06-06 14:56 UTC, ZeRiix commented on vue/src/components/TheCarousel.vue
> +<style scoped>
@mathcovax on utilise ou pas les class tailwlind dans du css ou on interdit ?

2024-06-06 15:00 UTC, ZeRiix commented on duplo/src/fixtures/entities/product.ts
> +	`${faker.random.alpha({ count: 3 })}${faker.random.alphaNumeric(4).toUpperCase()}${faker.datatype.number({ min: 1000, max: 9999 })}`;
certains trucs de faker sont deprecated mais il n'existe pas d’équivalent. Le sku doit etre suffisamment complexe pour etre aléatoire et unique si quelqu'un à une idée de par quoi je pourrais remplacer ? (PS: autre qu'un timestamps évidement merci) @Maubry94 @mathcovax @Vitaalx

2024-06-06 15:10 UTC, ZeRiix commented on duplo/src/fixtures/entities/product.ts
> +	`${faker.random.alpha({ count: 3 })}${faker.random.alphaNumeric(4).toUpperCase()}${faker.datatype.number({ min: 1000, max: 9999 })}`;
il existe ca qui peux etre similaire et faire a peut pret le taf:
`faker.commerce.isbn() // '978-0-692-82459-7'`

2024-06-06 21:45 UTC, mathcovax commented on duplo/src/fixtures/entities/product.ts
> +	`${faker.random.alpha({ count: 3 })}${faker.random.alphaNumeric(4).toUpperCase()}${faker.datatype.number({ min: 1000, max: 9999 })}`;
on va générer un uuidv7 avec la lib

2024-06-06 21:47 UTC, mathcovax commented on vue/src/components/TheCarousel.vue
> +<style scoped>
utilise tailwind

2024-06-06 21:47 UTC, mathcovax commented on vue/src/components/TheSection.vue
> +<style scoped>
same

2024-06-07 13:39 UTC, ZeRiix commented on vue/src/components/TheCarousel.vue
> +<style scoped>
c'est du tailwind

2024-06-07 15:22 UTC, mathcovax approved these changes

2024-06-07 15:22 UTC, merged